# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('1', '\u5b9e\u9a8c\u5ba4\u7b80\u4ecb'), ('2', '\u65b0\u95fb\u52a8\u6001'), ('3', '\u901a\u77e5\u516c\u544a')], default=1, max_length=1, verbose_name='\u6587\u7ae0\u5206\u7c7b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='url',
            field=models.CharField(default=1, max_length=100, verbose_name='\u5bf9\u5e94\u7f51\u5740'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='picture',
            table='picture',
        ),
    ]
