# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20171110_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='student_category',
            field=models.CharField(choices=[('1', '\u672c\u79d1\u751f'), ('2', '\u7814\u7a76\u751f'), ('3', '\u535a\u58eb\u751f')], default=1, max_length=1, verbose_name='\u5b66\u751f\u5206\u7c7b'),
            preserve_default=False,
        ),
    ]
