# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_article_student_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='student_category',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('kydt', '\u79d1\u7814\u52a8\u6001'), ('yjcg', '\u7814\u7a76\u6210\u679c'), ('bks', '\u672c\u79d1\u751f'), ('yjs', '\u7814\u7a76\u751f'), ('bss', '\u535a\u58eb\u751f')], max_length=20, verbose_name='\u6587\u7ae0\u5206\u7c7b'),
        ),
    ]
