# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20171111_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u79d1\u7814\u52a8\u6001\u6807\u9898')),
                ('description', models.TextField(verbose_name='\u52a8\u6001\u7b80\u4ecb')),
            ],
            options={
                'db_table': 'research',
            },
        ),
        migrations.RemoveField(
            model_name='picture',
            name='url',
        ),
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default=1, max_length=25, verbose_name='\u56fe\u7247\u540d\u79f0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='timestamp',
            field=models.CharField(blank=True, max_length=25, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
